import { User } from "@/types/users";

const users: User[] = [
  {
    id: 1,
    profileImage: "/user.png",
    name: "Michael Farrior",
    email: "michaelfarrior@farriorthomes.com",
    phone: "(708) 953-1795",
    company: "Farrior Homes",
    address: "2715 Ash Dr, San Jose, CA 95125",
    subscription: "Premium",
    propertiesOwn: 12,
    propertiesBuy: 4,
    propertiesSell: 8,
    createdAt: "2024-11-02",
  },
  {
    id: 2,
    profileImage: "/user.png",
    name: "Sarah Agent",
    email: "sarah@oakrealty.com",
    phone: "(555) 123-4567",
    company: "Oak Realty",
    address: "Middle Badda, Dhaka, Bangladesh",
    subscription: "Basic",
    propertiesOwn: 3,
    propertiesBuy: 1,
    propertiesSell: 2,
    createdAt: "2025-01-05",
  },
  {
    id: 3,
    profileImage: "/user.png",
    name: "Downtown Realty",
    email: "info@citybrokers.com",
    phone: "(555) 987-6543",
    company: "City Brokers",
    address: "45 River Rd, Chicago",
    subscription: "Free",
    propertiesOwn: 2,
    propertiesBuy: 1,
    propertiesSell: 1,
    createdAt: "2024-12-12",
  },
  {
    id: 4,
    profileImage: "/user.png",
    name: "Urban Living Realty",
    email: "info@cityhomes.com",
    phone: "(555) 555-5555",
    company: "City Homes",
    address: "100 Skyline Dr, Chicago, 60614",
    subscription: "Basic",
    propertiesOwn: 5,
    propertiesBuy: 2,
    propertiesSell: 3,
    createdAt: "2025-03-20",
  },
  {
    id: 5,
    profileImage: "/user.png",
    name: "Family Homes Co.",
    email: "hello@suburbrealty.com",
    phone: "(555) 222-3333",
    company: "Suburb Realty",
    address: "78 Park Ave, Suburbia",
    subscription: "Premium",
    propertiesOwn: 9,
    propertiesBuy: 3,
    propertiesSell: 6,
    createdAt: "2024-08-01",
  },
  {
    id: 6,
    profileImage: "/user.png",
    name: "Green Living Homes",
    email: "info@sustainablerealty.com",
    phone: "(555) 999-9999",
    company: "Sustainable Realty",
    address: "Chicago, IL",
    subscription: "Free",
    propertiesOwn: 1,
    propertiesBuy: 0,
    propertiesSell: 1,
    createdAt: "2024-06-15",
  },
  {
    id: 7,
    profileImage: "/user.png",
    name: "Luxury Living",
    email: "info@luxuryliving.com",
    phone: "(555) 777-7777",
    company: "Luxury Living",
    address: "Chicago, IL",
    subscription: "Premium",
    propertiesOwn: 7,
    propertiesBuy: 2,
    propertiesSell: 5,
    createdAt: "2024-10-09",
  },
  {
    id: 8,
    profileImage: "/user.png",
    name: "Coastal Living",
    email: "info@coastalliving.com",
    phone: "(555) 404-0404",
    company: "Coastal Living",
    address: "Beachfront, CA",
    subscription: "Basic",
    propertiesOwn: 4,
    propertiesBuy: 1,
    propertiesSell: 3,
    createdAt: "2025-02-01",
  },
  {
    id: 9,
    profileImage: "/user.png",
    name: "Creative Living",
    email: "info@creativeliving.com",
    phone: "(555) 505-0505",
    company: "Creative Living",
    address: "Arts District",
    subscription: "Free",
    propertiesOwn: 0,
    propertiesBuy: 0,
    propertiesSell: 0,
    createdAt: "2024-01-10",
  },
  {
    id: 10,
    profileImage: "/user.png",
    name: "Rural Living Realty",
    email: "info@rurallivingrealty.com",
    phone: "(555) 808-0808",
    company: "Rural Living Realty",
    address: "Rural Area",
    subscription: "Basic",
    propertiesOwn: 6,
    propertiesBuy: 2,
    propertiesSell: 4,
    createdAt: "2023-09-30",
  },
];

export function getAllUsers() {
  return users;
}

export function getUserById(id: number) {
  return users.find((u) => u.id === id) ?? null;
}

export default users;
